Experiment 2 - Introduction to Python Programming

1) Normalization Problem

In [14]:
import numpy as np

X = np.random.rand(5, 5)

mean_of_x = X.mean()
std_of_X = X.std()

X_normalized = (X - mean_of_x) / std_of_X

np.save('X_normalized.npy', X_normalized)

X_loaded = np.load('X_normalized.npy')
print("Normalized array:")
print(X_loaded)

Normalized array:
[[ 0.976564    0.73664067 -0.73724194  0.89791667 -1.56224445]
 [ 0.07137883  0.09149763 -0.69104448  0.0591272  -0.03368885]
 [-0.22102832  0.74961602  1.05147327  0.08755873 -0.05237739]
 [-1.5689826   1.13222518 -0.00354155  0.885864   -1.63705684]
 [ 1.22182822 -1.65831953  0.32585151 -1.78234436  1.66032838]]


2) Divisible by 3 Problem

In [24]:
import numpy as np

integers = np.arange(1, 101)

Y = integers.reshape(10, 10) ** 2

div_by_3 = Y[Y % 3 == 0]

np.save('div_by_3.npy', div_by_3)

print("10x10 ndarray:")
print(Y)
print("\nElements in the ndarray that are divisible by 3:")
print(div_by_3)

10x10 ndarray:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements in the ndarray that are divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
